-- Doctrine Migration File Generated on 2024-02-22 16:47:44

-- Version sql\migrations\Version20240222164723
CREATE TABLE users
(
    platform_id             INT                                  NOT NULL,
    platform_authentication VARCHAR(255)                         NOT NULL,
    first_name              VARCHAR(255) DEFAULT NULL,
    last_name               VARCHAR(255) DEFAULT NULL,
    hash_key                VARCHAR(255)                         NOT NULL,
    id                      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_date            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX UNIQ_1483A5E9FFE6496F ON users (platform_id);
CREATE UNIQUE INDEX UNIQ_1483A5E989A60D9A ON users (hash_key);
